"""empty message

Revision ID: defb8f329ea9
Revises: c93a2d1e55f5
Create Date: 2018-10-12 10:02:10.592935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defb8f329ea9'
down_revision = 'c93a2d1e55f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('race', 'id_round',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('race_participants', 'id_race',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('race_participants', 'id_snail',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('race_result', 'id_race_participants',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('snail', 'trainer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('snail', 'trainer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('race_result', 'id_race_participants',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('race_participants', 'id_snail',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('race_participants', 'id_race',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('race', 'id_round',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
